### ISSUE TITLE
Problem using GIT

### ISSUE THREAD

**Issue by kenpi2b** [openenergymonitor/documentation#3]
Hello,
I was trying to set up a Raspberry Pi 2 B  to use emoncms but began running intoissuesat the step that says:
Download emoncms using git:

$ git clone -b mqtt https://github.com/emoncms/emoncms.git
Once installed you can pull in updates with:

git pull

can you help me get it installed correctly? I am a Newbie with Raspbian(Debian-latest download) and Linux and Raspbery Pi 2 B with Arduino.

**Comment by chok** [comment]
Hello,

You just have to launch :
```
sudo apt-get install git
```

http://raspberrypi.stackexchange.com/questions/8658/can-i-install-git-on-raspbian :)
